baseURL = "https://idev-blog.web.app/"
languageCode = "en-us"
title = "NgocTD's Dev Log"

theme = "dark"

author = "Tran Duc Ngoc"
copyright = "Tran Duc Ngoc - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

paginate = 5
summaryLength = 30

[params]
    description = "NgocTD's blog about programming and other cool stuff"
    author = "Tran Duc Ngoc"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"
    # commento = "https://cloud.techpills.technology:54321/js/commento.js"
    # cactusCommentsSiteName = "gabmus.org"
    # cactusCommentsServerName = "cactus.chat"
    # cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"
    
    imageInArticlePreview = true

    enableShareOnFediverse = true

    enableRelatedArticles = true
    relatedArticlesNum = 2 
    forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.main]]
        identifier = "archguide"
        name = "Arch guide"
        url = "/archguide"
        weight = 99
    [[menu.icons]]
        identifier = "gitlab"
        name = "GitLab"
        url = "https://github.com/ngoctd314"
        weight = 10
