baseURL = "https://idev-blog.web.app/"
languageCode = "en-us"
title = "NgocTD's Dev Log"

theme = "dracula"

# author = "Tran Duc Ngoc"
copyright = "Tran Duc Ngoc"

# number of articles per page in the index
paginate = 5
# number of words for article sumaries
# 1 mean 1 tensen
summaryLength = 1

[params]
    # author = "Tran Duc Ngoc"
    description = "NgocTD's blog about programming and other cool stuff"     # meta data

    # posts = "posts"
    showPostsLink = true
    extraContentDirs = ["talk", "book review"]
    # showcaseDir = "showcase"

    # showSinglePageAsHome = false
    # homeSinglePage = "/guitar"

    logo = "/logo.png"
    favicon = "/favicon.png"
    # faviconIco = "/favicon.ico"
    # appletouch = "/apple-touch-icon.png"
    # svgicon = "/logo.svg"
    # icon512 = "/android-chrome-512x512.png"
    # commento = "https://cloud.techpills.technology:54321/js/commento.js"
    # cactusCommentsSiteName = "gabmus.org"
    # cactusCommentsServerName = "cactus.chat"
    # cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"
    
    # imageInArticlePreview = true

    # enableShareOnFediverse = true

    # enableRelatedArticles = true
    # relatedArticlesNum = 2 
    # forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
#    [[menu.main]]
#        identifier = "archguide"
#        name = "Arch guide"
#        url = "/archguide"
#        weight = 99
#    [[menu.icons]]
#        identifier = "gitlab"
#        name = "GitLab"
#        url = "https://github.com/ngoctd314"
#        weight = 10
