baseURL = "https://idev-blog.web.app/"
languageCode = "en-us"
title = "Dev's Log"

theme = "dracula"

# author = "Tran Duc Ngoc"
copyright = "Tran Duc Ngoc"

# number of articles per page in the index
paginate = 5
# number of words for article sumaries
# 1 mean 1 tensen
summaryLength = 40

[taxonomies]
    author = "authors"
    series = 'series'
    tag = "tags"

[params]
    # author = "Tran Duc Ngoc"
    description = "NgocTD's blog about programming and other cool stuff"     # meta data

    # posts = "posts"
    showPostsLink = true
    extraContentDirs = []
    # showcaseDir = "showcase"

    # showSinglePageAsHome = false
    # homeSinglePage = "/guitar"

    # navigation
    # showTags = false
    showAuthor = true
    showSeries = true
    showCategories = false

    logo = "/logo.png"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"

    paperCards = false  # enable paper card style; default false
    gridView = false
    # buttonTags = true

    imageInArticlePreview = true
    tagsInArticlePreview = true
    authorsInArticlePreview = true


    #navtype = "circles"
    #enableShadow = true
    menuStyle = "buttons" # standard, buttons

    enableFeatured = true

    underlineTitleLinks = false

    enableSidebarLayout = true
    tocInSidebar = true # if the sidebar is enabled, show the TOC in the sidebar

    infiniteScrolling = false  # activates infinite scrolling instead of regular pagination
    enableFooterColumns = false 
    enableJumbotron = false
    enableRelatedArticles = true
    relatedArticlesNum = 2

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "facebook"
        name = "Facebook"
        url = "https://www.facebook.com/ngoctd314"
        weight = 10
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/ngoctd314"
        weight = 11
    [[menu.icons]]
        identifier = "linkedin"
        name = "Email"
        url = "https://github.com/ngoctd314"
        weight = 12
#    [[menu.icons]]
#        identifier = "email"
#        name = "Email"
#        url = "mailto:tranngoc.contact@gmail.com"
#        weight = 13
#    [[menu.icons]]
#        identifier = "phone"
#        name = "Phone"
#        url = "tel:+84-33-9229-174"
#        weight = 14
